NEUTRAL_BIN = (15, -8)
RED_BIN = (-15, -8)
BLUE_BIN = (15, 3)
GREEN_BIN = (-15, 3)
UNKNOWN_BIN = NEUTRAL_BIN

COLOR_TO_BIN = {
    "RED": RED_BIN,
    "GREEN": GREEN_BIN,
    "BLUE": BLUE_BIN,
    "NEUTRAL": NEUTRAL_BIN,
}

CLASS_TO_BIN = {}

