from jetarm.config.paths import LEGO_YOLO_DATASET_DIR, MODELS_DIR, PRETRAINED_MODELS_DIR, YOLO_DATA_DIR


LEGO_YOLO_MODEL_PATH = MODELS_DIR / "lego_yolo11n.pt"
YOLO11N_MODEL_PATH = PRETRAINED_MODELS_DIR / "yolo11n.pt"
YOLO11S_MODEL_PATH = PRETRAINED_MODELS_DIR / "yolo11s.pt"
YOLOV8N_MODEL_PATH = PRETRAINED_MODELS_DIR / "yolov8n.pt"
DATASET_YAML_PATH = YOLO_DATA_DIR / "dataset.yaml"
LEGO_DATASET_YAML_PATH = LEGO_YOLO_DATASET_DIR / "data.yaml"

CONFIDENCE_THRESHOLD = 0.25
IMAGE_SIZE = 640
EPOCHS = 100
BATCH_SIZE = 16
TARGET_CLASSES = []
